{% set name = "cloudant" %}
{% set version = "2.9.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "db2650f605e9d4b5accbf9d15c990bc9568f87e1bef9c90b068f7b8b9d179cf3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .


requirements:
  build:
    - python
    - pip

  run:
    - python
    - requests >=2.7.0,<3.0.0

test:
  imports:
    - cloudant

about:
  home: https://github.com/cloudant/python-cloudant
  license: Apache 2.0
  license_file: {{ RECIPE_DIR }}/LICENSE
  license_family: Apache
  summary: 'Asynchronous Cloudant / CouchDB Interface'
  dev_url: https://github.com/cloudant/python-cloudant
  doc_url: https://python-cloudant.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
