{% set name = "cloudant" %}
{% set version = "2.5.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "a89b029777747c0fa6e1fc96efd5452feefae11cee7e3c310784a670f519f9ba" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - requests >=2.7.0,<3.0.0

test:
  imports:
    - cloudant

about:
  home: https://github.com/cloudant/python-cloudant
  license: Apache 2.0
  license_file: {{ RECIPE_DIR }}/LICENSE
  license_family: Apache
  summary: 'Asynchronous Cloudant / CouchDB Interface'
  dev_url: https://github.com/cloudant/python-cloudant
  doc_url: https://python-cloudant.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
