# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IQFs6Mn05GgHAudjXKAQGUBn9urQCPIJzxZ3IrcbQ+s0Br/Cmfu3kdxZQYYmZFsQXQkdLxozPlQdoA3cVAt3HFONBDQL/pGR/fp0DwVQ2ZANG++azlpbXhJKRRqIccCJUlR/w4P4cs9Rq+f+TvjAYNZA0y6L2Tqhfn2HF2Nmn4VCWXWf7Qlz03XYM7ptq95+LHX9trNZuEL4q/qLluZN4Woz+I5hHQz1+pmdMZdCbAFTS+wX8c/kapmx856uiGA1eey3vKg8f44SZ4orr4/qm5sCue2x3o22Jnk2qD9dA+TznQpSpARAxYiN7IpQoL5t2xujtFC810fX3BXjaf5rmvFmkFISHTWsUdU91Onu7z9So+gLryEs8VyOrrtN7dp74pTVDEXkY4TK33/MDIc8qeGpZaLH2+4Xzwmq89veECR6hLMS8XU0j+AsvHJmeSSZg83Qc849XcHYJ2kfr167F1FquCw94y4j/w44rbtdCdK/3l9hiTXXbAaNhw4xl0wEVjkTuT5y6uSK2hi3XyctlmG3RgftoDIr9cn4wrB5qt7FmoIgstjoCzhRCQ7V3ZZy+z6JfWvsLPlaTVFZwsdEu79E98Klpylm9zFipZxiT0gXetwCEQySqqPYnsaJU8mhUqTYM2JvSBzQitNdfYmmhgvFmPW3StiFFMM9dRTti5I="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
