travis:
  secure:
    BINSTAR_TOKEN: fkttUWccxv+IPxLYssrFu4oIye/Al1uPcSonEYSvtfbZA2GgZwpsidvnjZwpRe9LmhLhk123nTHVQCZK6kCAHbK6XQ+ZBlAgMl0fpj6c7nTXhEmjF2pyv1dX9D1nQHwG2GMMSEqvqALeOlqk24l2Mbv/BsOAAroKeq7PwTqgxWiGFFRliF78gSikpZc2iqEy+hL0pFFCB1iblTcaVhHHJlsTENe79S9+jQu9FYwOvYJLwVVnbVuNpHt6Ce/bn7C0hey2v52bkKI+m78B9VVBal+vE4O6M7uffyqWgfNIAmLByspvW0BVoJS0sGZ68CbJ2kUWRBR+8T8alt8xHjf2AOIcgILFbUn6FpGse/rDbxKf1ssj7/X7G3OJZ/kBE/sDecV9cYgenUGAQufEAA+Rog9Pydj4mHL5H0G0HYAtMg68yXd6lQzd/i5IqqTIkcEFx/iXQukKCZZeCFk9UYHEgmsNLT+kU7c4lEMzVFpuPw4XOS58q7QMdixd5EpSU32OYMhoWefsmI+eHzq0bUg4aRVcGi7DkM79CFQcGBSKQe+LDH3egOeXBdQecz+xsAtFcjXxCbTldK2J0nUE8oFUYq0o0eHwZIxYX3eoOeMWKvaImRbAURyizRao1nwqw75wz6qcjr2scUIB39ZgefCSTYPkLWVgnB8q/19IPZSYJlc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
