travis:
  secure:
    BINSTAR_TOKEN: IQFs6Mn05GgHAudjXKAQGUBn9urQCPIJzxZ3IrcbQ+s0Br/Cmfu3kdxZQYYmZFsQXQkdLxozPlQdoA3cVAt3HFONBDQL/pGR/fp0DwVQ2ZANG++azlpbXhJKRRqIccCJUlR/w4P4cs9Rq+f+TvjAYNZA0y6L2Tqhfn2HF2Nmn4VCWXWf7Qlz03XYM7ptq95+LHX9trNZuEL4q/qLluZN4Woz+I5hHQz1+pmdMZdCbAFTS+wX8c/kapmx856uiGA1eey3vKg8f44SZ4orr4/qm5sCue2x3o22Jnk2qD9dA+TznQpSpARAxYiN7IpQoL5t2xujtFC810fX3BXjaf5rmvFmkFISHTWsUdU91Onu7z9So+gLryEs8VyOrrtN7dp74pTVDEXkY4TK33/MDIc8qeGpZaLH2+4Xzwmq89veECR6hLMS8XU0j+AsvHJmeSSZg83Qc849XcHYJ2kfr167F1FquCw94y4j/w44rbtdCdK/3l9hiTXXbAaNhw4xl0wEVjkTuT5y6uSK2hi3XyctlmG3RgftoDIr9cn4wrB5qt7FmoIgstjoCzhRCQ7V3ZZy+z6JfWvsLPlaTVFZwsdEu79E98Klpylm9zFipZxiT0gXetwCEQySqqPYnsaJU8mhUqTYM2JvSBzQitNdfYmmhgvFmPW3StiFFMM9dRTti5I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
