travis:
  secure:
    BINSTAR_TOKEN: ZDUOXMHFzgx2CRVFEpd9VlKH3Ht1JK5ktdPIBlP9NKuer9dVD/gpPEXf5JMelYyc3WBatUVqbdG20EEgUyZ8EQ9DnOasEhWvBcpEHOmJ16+43rTZ0w9i7k+5Px89cCl8J1ss9K0MbFYANdRDLFToW8MAonqtXHR9d3gOj9aXcqzjAp7/+0TQSZmle2Fo/fwgI3BXBFRd+x5+WvoTmrgibkqXWfReURZ78ruUHxI0cko5yD04JNgNkbd9zooDh70vJHEgK4s29EdAWcKiNqADL4fpfbIsdYXcLHInxHj38a2T8DWzhzgNRY86xpp3utYpM0tJxSdcIs48apTLzlTMmXh4vxQy6Lczkz9A6F1VCiVTzZGP31ynNNz6y3X8Oyi6ie2rRP3WfMw04ED0h16bSD4uPnv8rynnNjv6kJzJdhx73OBqhLFe3bBzZM4Zk+NURy/RBgWSw6zPKrzET7DIQpcqsVGeEioEvDstD10MM5+qYcpDQ722AJEBbxUQzMz7eRgf6cEHeH2dhcyqwJgl77PJbuXcnJNuwKPUFjF+RzkhQKCJIsJ1VpmSuwFG4AI1H+54xc0KoCUaRz0d1DKlZmaG8Q5lTnc3Ko1hpGMPWb2lMo0zhN0W2aSkWpIIPUHQG03xkBlUuqbvFuw3ezErKyWg1jadk830pSi+MozD9Gs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
